// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/job.proto

package jobpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ScheduleAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateJobRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *CreateJobRequest) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

type UpdateJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ScheduleAt    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateJobRequest) Reset() {
	*x = UpdateJobRequest{}
	mi := &file_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateJobRequest) ProtoMessage() {}

func (x *UpdateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateJobRequest.ProtoReflect.Descriptor instead.
func (*UpdateJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UpdateJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *UpdateJobRequest) GetScheduleAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleAt
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_proto_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{2}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_proto_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{3}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	StartDate     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=endDate,proto3" json:"endDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{4}
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListJobsRequest) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ListJobsRequest) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

type ListFailedJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailedJobsRequest) Reset() {
	*x = ListFailedJobsRequest{}
	mi := &file_proto_job_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailedJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailedJobsRequest) ProtoMessage() {}

func (x *ListFailedJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailedJobsRequest.ProtoReflect.Descriptor instead.
func (*ListFailedJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{5}
}

func (x *ListFailedJobsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFailedJobsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type Job struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	Retry         int32                  `protobuf:"varint,6,opt,name=retry,proto3" json:"retry,omitempty"`
	MaxRetry      int32                  `protobuf:"varint,7,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`
	ScheduleAt    string                 `protobuf:"bytes,8,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ManualRetry   int32                  `protobuf:"varint,11,opt,name=manual_retry,json=manualRetry,proto3" json:"manual_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_proto_job_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{6}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *Job) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Job) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *Job) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Job) GetScheduleAt() string {
	if x != nil {
		return x.ScheduleAt
	}
	return ""
}

func (x *Job) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Job) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Job) GetManualRetry() int32 {
	if x != nil {
		return x.ManualRetry
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*Job                 `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_job_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{7}
}

func (x *ListJobsResponse) GetJobs() []*Job {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListJobsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListJobsResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetJobLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsRequest) Reset() {
	*x = GetJobLogsRequest{}
	mi := &file_proto_job_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsRequest) ProtoMessage() {}

func (x *GetJobLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsRequest.ProtoReflect.Descriptor instead.
func (*GetJobLogsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{8}
}

func (x *GetJobLogsRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobLogsAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsAdminRequest) Reset() {
	*x = GetJobLogsAdminRequest{}
	mi := &file_proto_job_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsAdminRequest) ProtoMessage() {}

func (x *GetJobLogsAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsAdminRequest.ProtoReflect.Descriptor instead.
func (*GetJobLogsAdminRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{9}
}

func (x *GetJobLogsAdminRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     string                 `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLog) Reset() {
	*x = JobLog{}
	mi := &file_proto_job_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLog) ProtoMessage() {}

func (x *JobLog) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLog.ProtoReflect.Descriptor instead.
func (*JobLog) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{10}
}

func (x *JobLog) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *JobLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetJobLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*JobLog              `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobLogsResponse) Reset() {
	*x = GetJobLogsResponse{}
	mi := &file_proto_job_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobLogsResponse) ProtoMessage() {}

func (x *GetJobLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobLogsResponse.ProtoReflect.Descriptor instead.
func (*GetJobLogsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{11}
}

func (x *GetJobLogsResponse) GetLogs() []*JobLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

type RetryJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobRequest) Reset() {
	*x = RetryJobRequest{}
	mi := &file_proto_job_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobRequest) ProtoMessage() {}

func (x *RetryJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobRequest.ProtoReflect.Descriptor instead.
func (*RetryJobRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{12}
}

func (x *RetryJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type RetryJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewJobId      string                 `protobuf:"bytes,1,opt,name=new_job_id,json=newJobId,proto3" json:"new_job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryJobResponse) Reset() {
	*x = RetryJobResponse{}
	mi := &file_proto_job_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryJobResponse) ProtoMessage() {}

func (x *RetryJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryJobResponse.ProtoReflect.Descriptor instead.
func (*RetryJobResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{13}
}

func (x *RetryJobResponse) GetNewJobId() string {
	if x != nil {
		return x.NewJobId
	}
	return ""
}

type GetJobStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatsRequest) Reset() {
	*x = GetJobStatsRequest{}
	mi := &file_proto_job_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatsRequest) ProtoMessage() {}

func (x *GetJobStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatsRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{14}
}

type GetJobStatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalJobs        int32                  `protobuf:"varint,1,opt,name=total_jobs,json=totalJobs,proto3" json:"total_jobs,omitempty"`
	TotalSuccessJobs int32                  `protobuf:"varint,2,opt,name=total_success_jobs,json=totalSuccessJobs,proto3" json:"total_success_jobs,omitempty"`
	TotalFailedJobs  int32                  `protobuf:"varint,3,opt,name=total_failed_jobs,json=totalFailedJobs,proto3" json:"total_failed_jobs,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetJobStatsResponse) Reset() {
	*x = GetJobStatsResponse{}
	mi := &file_proto_job_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatsResponse) ProtoMessage() {}

func (x *GetJobStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatsResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{15}
}

func (x *GetJobStatsResponse) GetTotalJobs() int32 {
	if x != nil {
		return x.TotalJobs
	}
	return 0
}

func (x *GetJobStatsResponse) GetTotalSuccessJobs() int32 {
	if x != nil {
		return x.TotalSuccessJobs
	}
	return 0
}

func (x *GetJobStatsResponse) GetTotalFailedJobs() int32 {
	if x != nil {
		return x.TotalFailedJobs
	}
	return 0
}

type GetJobMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Bucket        string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"` // hour, day
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobMetricsRequest) Reset() {
	*x = GetJobMetricsRequest{}
	mi := &file_proto_job_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobMetricsRequest) ProtoMessage() {}

func (x *GetJobMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetJobMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobMetricsRequest) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *GetJobMetricsRequest) GetTo() *timestamppb.Timestamp {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *GetJobMetricsRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type MetricBucket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            string                 `protobuf:"bytes,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Created       int32                  `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Completed     int32                  `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Failed        int32                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricBucket) Reset() {
	*x = MetricBucket{}
	mi := &file_proto_job_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBucket) ProtoMessage() {}

func (x *MetricBucket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBucket.ProtoReflect.Descriptor instead.
func (*MetricBucket) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{17}
}

func (x *MetricBucket) GetTs() string {
	if x != nil {
		return x.Ts
	}
	return ""
}

func (x *MetricBucket) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *MetricBucket) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *MetricBucket) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

type GetJobMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []*MetricBucket        `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobMetricsResponse) Reset() {
	*x = GetJobMetricsResponse{}
	mi := &file_proto_job_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobMetricsResponse) ProtoMessage() {}

func (x *GetJobMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_job_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetJobMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_job_proto_rawDescGZIP(), []int{18}
}

func (x *GetJobMetricsResponse) GetBuckets() []*MetricBucket {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_proto_job_proto protoreflect.FileDescriptor

const file_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/job.proto\x12\x03job\x1a\x1fgoogle/protobuf/timestamp.proto\x1a'googleapis/google/api/annotations.proto\"\x94\x01\n" +
	"\x10CreateJobRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12;\n" +
	"\vschedule_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"scheduleAt\"\x80\x01\n" +
	"\x10UpdateJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12;\n" +
	"\vschedule_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"scheduleAt\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"<\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xc7\x01\n" +
	"\x0fListJobsRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x128\n" +
	"\tstartDate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartDate\x124\n" +
	"\aendDate\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendDate\"E\n" +
	"\x15ListFailedJobsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"\xae\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x12\x14\n" +
	"\x05retry\x18\x06 \x01(\x05R\x05retry\x12\x1b\n" +
	"\tmax_retry\x18\a \x01(\x05R\bmaxRetry\x12\x1f\n" +
	"\vschedule_at\x18\b \x01(\tR\n" +
	"scheduleAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12!\n" +
	"\fmanual_retry\x18\v \x01(\x05R\vmanualRetry\"t\n" +
	"\x10ListJobsResponse\x12\x1c\n" +
	"\x04jobs\x18\x01 \x03(\v2\b.job.JobR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"*\n" +
	"\x11GetJobLogsRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"/\n" +
	"\x16GetJobLogsAdminRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"b\n" +
	"\x06JobLog\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\"\n" +
	"\ferrorMessage\x18\x03 \x01(\tR\ferrorMessage\"5\n" +
	"\x12GetJobLogsResponse\x12\x1f\n" +
	"\x04logs\x18\x01 \x03(\v2\v.job.JobLogR\x04logs\"(\n" +
	"\x0fRetryJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"0\n" +
	"\x10RetryJobResponse\x12\x1c\n" +
	"\n" +
	"new_job_id\x18\x01 \x01(\tR\bnewJobId\"\x14\n" +
	"\x12GetJobStatsRequest\"\x8e\x01\n" +
	"\x13GetJobStatsResponse\x12\x1d\n" +
	"\n" +
	"total_jobs\x18\x01 \x01(\x05R\ttotalJobs\x12,\n" +
	"\x12total_success_jobs\x18\x02 \x01(\x05R\x10totalSuccessJobs\x12*\n" +
	"\x11total_failed_jobs\x18\x03 \x01(\x05R\x0ftotalFailedJobs\"\x8a\x01\n" +
	"\x14GetJobMetricsRequest\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x12*\n" +
	"\x02to\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02to\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\"n\n" +
	"\fMetricBucket\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\tR\x02ts\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\x05R\tcompleted\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\"D\n" +
	"\x15GetJobMetricsResponse\x12+\n" +
	"\abuckets\x18\x01 \x03(\v2\x11.job.MetricBucketR\abuckets2\x8a\a\n" +
	"\n" +
	"JobService\x12M\n" +
	"\tCreateJob\x12\x15.job.CreateJobRequest\x1a\x10.job.JobResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/jobs\x12V\n" +
	"\tUpdateJob\x12\x15.job.UpdateJobRequest\x1a\x10.job.JobResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/api/v1/jobs/{job_id}\x12S\n" +
	"\tCancelJob\x12\x15.job.CancelJobRequest\x1a\x10.job.JobResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/api/v1/jobs/{job_id}\x12M\n" +
	"\bListJobs\x12\x14.job.ListJobsRequest\x1a\x15.job.ListJobsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12`\n" +
	"\x0eListFailedJobs\x12\x1a.job.ListFailedJobsRequest\x1a\x15.job.ListJobsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/jobs/failed\x12a\n" +
	"\n" +
	"GetJobLogs\x12\x16.job.GetJobLogsRequest\x1a\x17.job.GetJobLogsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v1/jobs/{job_id}/logs\x12\\\n" +
	"\vGetJobStats\x12\x17.job.GetJobStatsRequest\x1a\x18.job.GetJobStatsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/jobs/stats\x12d\n" +
	"\rGetJobMetrics\x12\x19.job.GetJobMetricsRequest\x1a\x1a.job.GetJobMetricsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/v1/jobs/metrics\x12G\n" +
	"\x0fGetJobAdminLogs\x12\x1b.job.GetJobLogsAdminRequest\x1a\x17.job.GetJobLogsResponse\x12_\n" +
	"\bRetryJob\x12\x14.job.RetryJobRequest\x1a\x15.job.RetryJobResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/jobs/{job_id}/retryB\x16Z\x14internal/proto/jobpbb\x06proto3"

var (
	file_proto_job_proto_rawDescOnce sync.Once
	file_proto_job_proto_rawDescData []byte
)

func file_proto_job_proto_rawDescGZIP() []byte {
	file_proto_job_proto_rawDescOnce.Do(func() {
		file_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)))
	})
	return file_proto_job_proto_rawDescData
}

var file_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_job_proto_goTypes = []any{
	(*CreateJobRequest)(nil),       // 0: job.CreateJobRequest
	(*UpdateJobRequest)(nil),       // 1: job.UpdateJobRequest
	(*CancelJobRequest)(nil),       // 2: job.CancelJobRequest
	(*JobResponse)(nil),            // 3: job.JobResponse
	(*ListJobsRequest)(nil),        // 4: job.ListJobsRequest
	(*ListFailedJobsRequest)(nil),  // 5: job.ListFailedJobsRequest
	(*Job)(nil),                    // 6: job.Job
	(*ListJobsResponse)(nil),       // 7: job.ListJobsResponse
	(*GetJobLogsRequest)(nil),      // 8: job.GetJobLogsRequest
	(*GetJobLogsAdminRequest)(nil), // 9: job.GetJobLogsAdminRequest
	(*JobLog)(nil),                 // 10: job.JobLog
	(*GetJobLogsResponse)(nil),     // 11: job.GetJobLogsResponse
	(*RetryJobRequest)(nil),        // 12: job.RetryJobRequest
	(*RetryJobResponse)(nil),       // 13: job.RetryJobResponse
	(*GetJobStatsRequest)(nil),     // 14: job.GetJobStatsRequest
	(*GetJobStatsResponse)(nil),    // 15: job.GetJobStatsResponse
	(*GetJobMetricsRequest)(nil),   // 16: job.GetJobMetricsRequest
	(*MetricBucket)(nil),           // 17: job.MetricBucket
	(*GetJobMetricsResponse)(nil),  // 18: job.GetJobMetricsResponse
	(*timestamppb.Timestamp)(nil),  // 19: google.protobuf.Timestamp
}
var file_proto_job_proto_depIdxs = []int32{
	19, // 0: job.CreateJobRequest.schedule_at:type_name -> google.protobuf.Timestamp
	19, // 1: job.UpdateJobRequest.schedule_at:type_name -> google.protobuf.Timestamp
	19, // 2: job.ListJobsRequest.startDate:type_name -> google.protobuf.Timestamp
	19, // 3: job.ListJobsRequest.endDate:type_name -> google.protobuf.Timestamp
	6,  // 4: job.ListJobsResponse.jobs:type_name -> job.Job
	10, // 5: job.GetJobLogsResponse.logs:type_name -> job.JobLog
	19, // 6: job.GetJobMetricsRequest.from:type_name -> google.protobuf.Timestamp
	19, // 7: job.GetJobMetricsRequest.to:type_name -> google.protobuf.Timestamp
	17, // 8: job.GetJobMetricsResponse.buckets:type_name -> job.MetricBucket
	0,  // 9: job.JobService.CreateJob:input_type -> job.CreateJobRequest
	1,  // 10: job.JobService.UpdateJob:input_type -> job.UpdateJobRequest
	2,  // 11: job.JobService.CancelJob:input_type -> job.CancelJobRequest
	4,  // 12: job.JobService.ListJobs:input_type -> job.ListJobsRequest
	5,  // 13: job.JobService.ListFailedJobs:input_type -> job.ListFailedJobsRequest
	8,  // 14: job.JobService.GetJobLogs:input_type -> job.GetJobLogsRequest
	14, // 15: job.JobService.GetJobStats:input_type -> job.GetJobStatsRequest
	16, // 16: job.JobService.GetJobMetrics:input_type -> job.GetJobMetricsRequest
	9,  // 17: job.JobService.GetJobAdminLogs:input_type -> job.GetJobLogsAdminRequest
	12, // 18: job.JobService.RetryJob:input_type -> job.RetryJobRequest
	3,  // 19: job.JobService.CreateJob:output_type -> job.JobResponse
	3,  // 20: job.JobService.UpdateJob:output_type -> job.JobResponse
	3,  // 21: job.JobService.CancelJob:output_type -> job.JobResponse
	7,  // 22: job.JobService.ListJobs:output_type -> job.ListJobsResponse
	7,  // 23: job.JobService.ListFailedJobs:output_type -> job.ListJobsResponse
	11, // 24: job.JobService.GetJobLogs:output_type -> job.GetJobLogsResponse
	15, // 25: job.JobService.GetJobStats:output_type -> job.GetJobStatsResponse
	18, // 26: job.JobService.GetJobMetrics:output_type -> job.GetJobMetricsResponse
	11, // 27: job.JobService.GetJobAdminLogs:output_type -> job.GetJobLogsResponse
	13, // 28: job.JobService.RetryJob:output_type -> job.RetryJobResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_job_proto_init() }
func file_proto_job_proto_init() {
	if File_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_job_proto_rawDesc), len(file_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_job_proto_goTypes,
		DependencyIndexes: file_proto_job_proto_depIdxs,
		MessageInfos:      file_proto_job_proto_msgTypes,
	}.Build()
	File_proto_job_proto = out.File
	file_proto_job_proto_goTypes = nil
	file_proto_job_proto_depIdxs = nil
}
