// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/scheduler.proto

package schedulerpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobResultStatus int32

const (
	JobResultStatus_JOB_RESULT_UNKNOWN JobResultStatus = 0
	JobResultStatus_JOB_RESULT_SUCCESS JobResultStatus = 1
	JobResultStatus_JOB_RESULT_FAILED  JobResultStatus = 2
)

// Enum value maps for JobResultStatus.
var (
	JobResultStatus_name = map[int32]string{
		0: "JOB_RESULT_UNKNOWN",
		1: "JOB_RESULT_SUCCESS",
		2: "JOB_RESULT_FAILED",
	}
	JobResultStatus_value = map[string]int32{
		"JOB_RESULT_UNKNOWN": 0,
		"JOB_RESULT_SUCCESS": 1,
		"JOB_RESULT_FAILED":  2,
	}
)

func (x JobResultStatus) Enum() *JobResultStatus {
	p := new(JobResultStatus)
	*p = x
	return p
}

func (x JobResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobResultStatus) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[0]
}

func (x JobResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobResultStatus.Descriptor instead.
func (JobResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

type WorkerStatus int32

const (
	WorkerStatus_WORKER_STATUS_UNKNOWN WorkerStatus = 0
	WorkerStatus_WORKER_STATUS_ONLINE  WorkerStatus = 1
	WorkerStatus_WORKER_STATUS_BUSY    WorkerStatus = 2
	WorkerStatus_WORKER_STATUS_STALE   WorkerStatus = 3
	WorkerStatus_WORKER_STATUS_OFFLINE WorkerStatus = 4
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "WORKER_STATUS_UNKNOWN",
		1: "WORKER_STATUS_ONLINE",
		2: "WORKER_STATUS_BUSY",
		3: "WORKER_STATUS_STALE",
		4: "WORKER_STATUS_OFFLINE",
	}
	WorkerStatus_value = map[string]int32{
		"WORKER_STATUS_UNKNOWN": 0,
		"WORKER_STATUS_ONLINE":  1,
		"WORKER_STATUS_BUSY":    2,
		"WORKER_STATUS_STALE":   3,
		"WORKER_STATUS_OFFLINE": 4,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[1].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[1]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Progress      int64                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type JobResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        JobResultStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=scheduler.JobResultStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Stacktrace    string                 `protobuf:"bytes,6,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Retry         int32                  `protobuf:"varint,8,opt,name=retry,proto3" json:"retry,omitempty"`
	ManualRetry   int32                  `protobuf:"varint,9,opt,name=manual_retry,json=manualRetry,proto3" json:"manual_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultRequest) Reset() {
	*x = JobResultRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultRequest) ProtoMessage() {}

func (x *JobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultRequest.ProtoReflect.Descriptor instead.
func (*JobResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *JobResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *JobResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobResultRequest) GetStatus() JobResultStatus {
	if x != nil {
		return x.Status
	}
	return JobResultStatus_JOB_RESULT_UNKNOWN
}

func (x *JobResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResultRequest) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

func (x *JobResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JobResultRequest) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *JobResultRequest) GetManualRetry() int32 {
	if x != nil {
		return x.ManualRetry
	}
	return 0
}

type RegisterWorkerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobTypes       []string               `protobuf:"bytes,3,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Timestamp      int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWorkerRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetJobTypes() []string {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *RegisterWorkerRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *RegisterWorkerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WorkerHeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AppId          string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId       string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobTypes       []string               `protobuf:"bytes,3,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	ActiveJobs     int32                  `protobuf:"varint,4,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,5,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	Timestamp      int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerHeartbeatRequest) Reset() {
	*x = WorkerHeartbeatRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeatRequest) ProtoMessage() {}

func (x *WorkerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *WorkerHeartbeatRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WorkerHeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerHeartbeatRequest) GetJobTypes() []string {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *WorkerHeartbeatRequest) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerHeartbeatRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *WorkerHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type UnregisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorkerRequest) Reset() {
	*x = UnregisterWorkerRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorkerRequest) ProtoMessage() {}

func (x *UnregisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterWorkerRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UnregisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *UnregisterWorkerRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type GetTenantRuntimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRuntimeRequest) Reset() {
	*x = GetTenantRuntimeRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRuntimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRuntimeRequest) ProtoMessage() {}

func (x *GetTenantRuntimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRuntimeRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRuntimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *GetTenantRuntimeRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type GetTenantRuntimeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AppId            string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	GeneratedAt      int64                  `protobuf:"varint,2,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	TotalReadyJobs   int64                  `protobuf:"varint,3,opt,name=total_ready_jobs,json=totalReadyJobs,proto3" json:"total_ready_jobs,omitempty"`
	TotalRunningJobs int64                  `protobuf:"varint,4,opt,name=total_running_jobs,json=totalRunningJobs,proto3" json:"total_running_jobs,omitempty"`
	TotalWorkers     int64                  `protobuf:"varint,5,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	OnlineWorkers    int64                  `protobuf:"varint,6,opt,name=online_workers,json=onlineWorkers,proto3" json:"online_workers,omitempty"`
	BusyWorkers      int64                  `protobuf:"varint,7,opt,name=busy_workers,json=busyWorkers,proto3" json:"busy_workers,omitempty"`
	Queues           []*QueueRuntime        `protobuf:"bytes,8,rep,name=queues,proto3" json:"queues,omitempty"`
	Workers          []*WorkerRuntime       `protobuf:"bytes,9,rep,name=workers,proto3" json:"workers,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTenantRuntimeResponse) Reset() {
	*x = GetTenantRuntimeResponse{}
	mi := &file_proto_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRuntimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRuntimeResponse) ProtoMessage() {}

func (x *GetTenantRuntimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRuntimeResponse.ProtoReflect.Descriptor instead.
func (*GetTenantRuntimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *GetTenantRuntimeResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *GetTenantRuntimeResponse) GetGeneratedAt() int64 {
	if x != nil {
		return x.GeneratedAt
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetTotalReadyJobs() int64 {
	if x != nil {
		return x.TotalReadyJobs
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetTotalRunningJobs() int64 {
	if x != nil {
		return x.TotalRunningJobs
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetTotalWorkers() int64 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetOnlineWorkers() int64 {
	if x != nil {
		return x.OnlineWorkers
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetBusyWorkers() int64 {
	if x != nil {
		return x.BusyWorkers
	}
	return 0
}

func (x *GetTenantRuntimeResponse) GetQueues() []*QueueRuntime {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *GetTenantRuntimeResponse) GetWorkers() []*WorkerRuntime {
	if x != nil {
		return x.Workers
	}
	return nil
}

type QueueRuntime struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	JobType               string                 `protobuf:"bytes,1,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	ReadyJobs             int64                  `protobuf:"varint,2,opt,name=ready_jobs,json=readyJobs,proto3" json:"ready_jobs,omitempty"`
	RunningJobs           int64                  `protobuf:"varint,3,opt,name=running_jobs,json=runningJobs,proto3" json:"running_jobs,omitempty"`
	RegisteredWorkers     int64                  `protobuf:"varint,4,opt,name=registered_workers,json=registeredWorkers,proto3" json:"registered_workers,omitempty"`
	BusyWorkers           int64                  `protobuf:"varint,5,opt,name=busy_workers,json=busyWorkers,proto3" json:"busy_workers,omitempty"`
	OldestReadyAgeSeconds int64                  `protobuf:"varint,6,opt,name=oldest_ready_age_seconds,json=oldestReadyAgeSeconds,proto3" json:"oldest_ready_age_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueueRuntime) Reset() {
	*x = QueueRuntime{}
	mi := &file_proto_scheduler_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRuntime) ProtoMessage() {}

func (x *QueueRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRuntime.ProtoReflect.Descriptor instead.
func (*QueueRuntime) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{7}
}

func (x *QueueRuntime) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *QueueRuntime) GetReadyJobs() int64 {
	if x != nil {
		return x.ReadyJobs
	}
	return 0
}

func (x *QueueRuntime) GetRunningJobs() int64 {
	if x != nil {
		return x.RunningJobs
	}
	return 0
}

func (x *QueueRuntime) GetRegisteredWorkers() int64 {
	if x != nil {
		return x.RegisteredWorkers
	}
	return 0
}

func (x *QueueRuntime) GetBusyWorkers() int64 {
	if x != nil {
		return x.BusyWorkers
	}
	return 0
}

func (x *QueueRuntime) GetOldestReadyAgeSeconds() int64 {
	if x != nil {
		return x.OldestReadyAgeSeconds
	}
	return 0
}

type WorkerRuntime struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobTypes       []string               `protobuf:"bytes,2,rep,name=job_types,json=jobTypes,proto3" json:"job_types,omitempty"`
	ActiveJobs     int32                  `protobuf:"varint,3,opt,name=active_jobs,json=activeJobs,proto3" json:"active_jobs,omitempty"`
	MaxConcurrency int32                  `protobuf:"varint,4,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"`
	LastSeen       int64                  `protobuf:"varint,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status         WorkerStatus           `protobuf:"varint,6,opt,name=status,proto3,enum=scheduler.WorkerStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkerRuntime) Reset() {
	*x = WorkerRuntime{}
	mi := &file_proto_scheduler_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRuntime) ProtoMessage() {}

func (x *WorkerRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRuntime.ProtoReflect.Descriptor instead.
func (*WorkerRuntime) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{8}
}

func (x *WorkerRuntime) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRuntime) GetJobTypes() []string {
	if x != nil {
		return x.JobTypes
	}
	return nil
}

func (x *WorkerRuntime) GetActiveJobs() int32 {
	if x != nil {
		return x.ActiveJobs
	}
	return 0
}

func (x *WorkerRuntime) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

func (x *WorkerRuntime) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *WorkerRuntime) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_WORKER_STATUS_UNKNOWN
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_scheduler_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{9}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\x1a'googleapis/google/api/annotations.proto\"\x97\x01\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x03R\bprogress\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xad\x02\n" +
	"\x10JobResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.scheduler.JobResultStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x06 \x01(\tR\n" +
	"stacktrace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05retry\x18\b \x01(\x05R\x05retry\x12!\n" +
	"\fmanual_retry\x18\t \x01(\x05R\vmanualRetry\"\xaf\x01\n" +
	"\x15RegisterWorkerRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tjob_types\x18\x03 \x03(\tR\bjobTypes\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xd1\x01\n" +
	"\x16WorkerHeartbeatRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tjob_types\x18\x03 \x03(\tR\bjobTypes\x12\x1f\n" +
	"\vactive_jobs\x18\x04 \x01(\x05R\n" +
	"activeJobs\x12'\n" +
	"\x0fmax_concurrency\x18\x05 \x01(\x05R\x0emaxConcurrency\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"k\n" +
	"\x17UnregisterWorkerRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"0\n" +
	"\x17GetTenantRuntimeRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x80\x03\n" +
	"\x18GetTenantRuntimeResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12!\n" +
	"\fgenerated_at\x18\x02 \x01(\x03R\vgeneratedAt\x12(\n" +
	"\x10total_ready_jobs\x18\x03 \x01(\x03R\x0etotalReadyJobs\x12,\n" +
	"\x12total_running_jobs\x18\x04 \x01(\x03R\x10totalRunningJobs\x12#\n" +
	"\rtotal_workers\x18\x05 \x01(\x03R\ftotalWorkers\x12%\n" +
	"\x0eonline_workers\x18\x06 \x01(\x03R\ronlineWorkers\x12!\n" +
	"\fbusy_workers\x18\a \x01(\x03R\vbusyWorkers\x12/\n" +
	"\x06queues\x18\b \x03(\v2\x17.scheduler.QueueRuntimeR\x06queues\x122\n" +
	"\aworkers\x18\t \x03(\v2\x18.scheduler.WorkerRuntimeR\aworkers\"\xf6\x01\n" +
	"\fQueueRuntime\x12\x19\n" +
	"\bjob_type\x18\x01 \x01(\tR\ajobType\x12\x1d\n" +
	"\n" +
	"ready_jobs\x18\x02 \x01(\x03R\treadyJobs\x12!\n" +
	"\frunning_jobs\x18\x03 \x01(\x03R\vrunningJobs\x12-\n" +
	"\x12registered_workers\x18\x04 \x01(\x03R\x11registeredWorkers\x12!\n" +
	"\fbusy_workers\x18\x05 \x01(\x03R\vbusyWorkers\x127\n" +
	"\x18oldest_ready_age_seconds\x18\x06 \x01(\x03R\x15oldestReadyAgeSeconds\"\xe1\x01\n" +
	"\rWorkerRuntime\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x1b\n" +
	"\tjob_types\x18\x02 \x03(\tR\bjobTypes\x12\x1f\n" +
	"\vactive_jobs\x18\x03 \x01(\x05R\n" +
	"activeJobs\x12'\n" +
	"\x0fmax_concurrency\x18\x04 \x01(\x05R\x0emaxConcurrency\x12\x1b\n" +
	"\tlast_seen\x18\x05 \x01(\x03R\blastSeen\x12/\n" +
	"\x06status\x18\x06 \x01(\x0e2\x17.scheduler.WorkerStatusR\x06status\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*X\n" +
	"\x0fJobResultStatus\x12\x16\n" +
	"\x12JOB_RESULT_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_RESULT_SUCCESS\x10\x01\x12\x15\n" +
	"\x11JOB_RESULT_FAILED\x10\x02*\x8f\x01\n" +
	"\fWorkerStatus\x12\x19\n" +
	"\x15WORKER_STATUS_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14WORKER_STATUS_ONLINE\x10\x01\x12\x16\n" +
	"\x12WORKER_STATUS_BUSY\x10\x02\x12\x17\n" +
	"\x13WORKER_STATUS_STALE\x10\x03\x12\x19\n" +
	"\x15WORKER_STATUS_OFFLINE\x10\x042\xd3\x03\n" +
	"\tScheduler\x128\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x0e.scheduler.Ack\x12;\n" +
	"\fReportResult\x12\x1b.scheduler.JobResultRequest\x1a\x0e.scheduler.Ack\x12B\n" +
	"\x0eRegisterWorker\x12 .scheduler.RegisterWorkerRequest\x1a\x0e.scheduler.Ack\x12D\n" +
	"\x0fWorkerHeartbeat\x12!.scheduler.WorkerHeartbeatRequest\x1a\x0e.scheduler.Ack\x12F\n" +
	"\x10UnregisterWorker\x12\".scheduler.UnregisterWorkerRequest\x1a\x0e.scheduler.Ack\x12}\n" +
	"\x10GetTenantRuntime\x12\".scheduler.GetTenantRuntimeRequest\x1a#.scheduler.GetTenantRuntimeResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/runtime/overviewB\x1bZ\x19internal/grpc/schedulerpbb\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_scheduler_proto_goTypes = []any{
	(JobResultStatus)(0),             // 0: scheduler.JobResultStatus
	(WorkerStatus)(0),                // 1: scheduler.WorkerStatus
	(*HeartbeatRequest)(nil),         // 2: scheduler.HeartbeatRequest
	(*JobResultRequest)(nil),         // 3: scheduler.JobResultRequest
	(*RegisterWorkerRequest)(nil),    // 4: scheduler.RegisterWorkerRequest
	(*WorkerHeartbeatRequest)(nil),   // 5: scheduler.WorkerHeartbeatRequest
	(*UnregisterWorkerRequest)(nil),  // 6: scheduler.UnregisterWorkerRequest
	(*GetTenantRuntimeRequest)(nil),  // 7: scheduler.GetTenantRuntimeRequest
	(*GetTenantRuntimeResponse)(nil), // 8: scheduler.GetTenantRuntimeResponse
	(*QueueRuntime)(nil),             // 9: scheduler.QueueRuntime
	(*WorkerRuntime)(nil),            // 10: scheduler.WorkerRuntime
	(*Ack)(nil),                      // 11: scheduler.Ack
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0,  // 0: scheduler.JobResultRequest.status:type_name -> scheduler.JobResultStatus
	9,  // 1: scheduler.GetTenantRuntimeResponse.queues:type_name -> scheduler.QueueRuntime
	10, // 2: scheduler.GetTenantRuntimeResponse.workers:type_name -> scheduler.WorkerRuntime
	1,  // 3: scheduler.WorkerRuntime.status:type_name -> scheduler.WorkerStatus
	2,  // 4: scheduler.Scheduler.Heartbeat:input_type -> scheduler.HeartbeatRequest
	3,  // 5: scheduler.Scheduler.ReportResult:input_type -> scheduler.JobResultRequest
	4,  // 6: scheduler.Scheduler.RegisterWorker:input_type -> scheduler.RegisterWorkerRequest
	5,  // 7: scheduler.Scheduler.WorkerHeartbeat:input_type -> scheduler.WorkerHeartbeatRequest
	6,  // 8: scheduler.Scheduler.UnregisterWorker:input_type -> scheduler.UnregisterWorkerRequest
	7,  // 9: scheduler.Scheduler.GetTenantRuntime:input_type -> scheduler.GetTenantRuntimeRequest
	11, // 10: scheduler.Scheduler.Heartbeat:output_type -> scheduler.Ack
	11, // 11: scheduler.Scheduler.ReportResult:output_type -> scheduler.Ack
	11, // 12: scheduler.Scheduler.RegisterWorker:output_type -> scheduler.Ack
	11, // 13: scheduler.Scheduler.WorkerHeartbeat:output_type -> scheduler.Ack
	11, // 14: scheduler.Scheduler.UnregisterWorker:output_type -> scheduler.Ack
	8,  // 15: scheduler.Scheduler.GetTenantRuntime:output_type -> scheduler.GetTenantRuntimeResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
