// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/scheduler.proto

package schedulerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobResultStatus int32

const (
	JobResultStatus_JOB_RESULT_UNKNOWN JobResultStatus = 0
	JobResultStatus_JOB_RESULT_SUCCESS JobResultStatus = 1
	JobResultStatus_JOB_RESULT_FAILED  JobResultStatus = 2
)

// Enum value maps for JobResultStatus.
var (
	JobResultStatus_name = map[int32]string{
		0: "JOB_RESULT_UNKNOWN",
		1: "JOB_RESULT_SUCCESS",
		2: "JOB_RESULT_FAILED",
	}
	JobResultStatus_value = map[string]int32{
		"JOB_RESULT_UNKNOWN": 0,
		"JOB_RESULT_SUCCESS": 1,
		"JOB_RESULT_FAILED":  2,
	}
)

func (x JobResultStatus) Enum() *JobResultStatus {
	p := new(JobResultStatus)
	*p = x
	return p
}

func (x JobResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scheduler_proto_enumTypes[0].Descriptor()
}

func (JobResultStatus) Type() protoreflect.EnumType {
	return &file_proto_scheduler_proto_enumTypes[0]
}

func (x JobResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobResultStatus.Descriptor instead.
func (JobResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Progress      int64                  `protobuf:"varint,4,opt,name=progress,proto3" json:"progress,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *HeartbeatRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetProgress() int64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type JobResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	WorkerId      string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Status        JobResultStatus        `protobuf:"varint,4,opt,name=status,proto3,enum=scheduler.JobResultStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Stacktrace    string                 `protobuf:"bytes,6,opt,name=stacktrace,proto3" json:"stacktrace,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Retry         int32                  `protobuf:"varint,8,opt,name=retry,proto3" json:"retry,omitempty"`
	ManualRetry   int32                  `protobuf:"varint,9,opt,name=manual_retry,json=manualRetry,proto3" json:"manual_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResultRequest) Reset() {
	*x = JobResultRequest{}
	mi := &file_proto_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResultRequest) ProtoMessage() {}

func (x *JobResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResultRequest.ProtoReflect.Descriptor instead.
func (*JobResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *JobResultRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResultRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *JobResultRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *JobResultRequest) GetStatus() JobResultStatus {
	if x != nil {
		return x.Status
	}
	return JobResultStatus_JOB_RESULT_UNKNOWN
}

func (x *JobResultRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *JobResultRequest) GetStacktrace() string {
	if x != nil {
		return x.Stacktrace
	}
	return ""
}

func (x *JobResultRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *JobResultRequest) GetRetry() int32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *JobResultRequest) GetManualRetry() int32 {
	if x != nil {
		return x.ManualRetry
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_scheduler_proto protoreflect.FileDescriptor

const file_proto_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scheduler.proto\x12\tscheduler\"\x97\x01\n" +
	"\x10HeartbeatRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12\x1a\n" +
	"\bprogress\x18\x04 \x01(\x03R\bprogress\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"\xad\x02\n" +
	"\x10JobResultRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.scheduler.JobResultStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12\x1e\n" +
	"\n" +
	"stacktrace\x18\x06 \x01(\tR\n" +
	"stacktrace\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05retry\x18\b \x01(\x05R\x05retry\x12!\n" +
	"\fmanual_retry\x18\t \x01(\x05R\vmanualRetry\"\x15\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok*X\n" +
	"\x0fJobResultStatus\x12\x16\n" +
	"\x12JOB_RESULT_UNKNOWN\x10\x00\x12\x16\n" +
	"\x12JOB_RESULT_SUCCESS\x10\x01\x12\x15\n" +
	"\x11JOB_RESULT_FAILED\x10\x022\x82\x01\n" +
	"\tScheduler\x128\n" +
	"\tHeartbeat\x12\x1b.scheduler.HeartbeatRequest\x1a\x0e.scheduler.Ack\x12;\n" +
	"\fReportResult\x12\x1b.scheduler.JobResultRequest\x1a\x0e.scheduler.AckB\x1bZ\x19internal/grpc/schedulerpbb\x06proto3"

var (
	file_proto_scheduler_proto_rawDescOnce sync.Once
	file_proto_scheduler_proto_rawDescData []byte
)

func file_proto_scheduler_proto_rawDescGZIP() []byte {
	file_proto_scheduler_proto_rawDescOnce.Do(func() {
		file_proto_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)))
	})
	return file_proto_scheduler_proto_rawDescData
}

var file_proto_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_scheduler_proto_goTypes = []any{
	(JobResultStatus)(0),     // 0: scheduler.JobResultStatus
	(*HeartbeatRequest)(nil), // 1: scheduler.HeartbeatRequest
	(*JobResultRequest)(nil), // 2: scheduler.JobResultRequest
	(*Ack)(nil),              // 3: scheduler.Ack
}
var file_proto_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.JobResultRequest.status:type_name -> scheduler.JobResultStatus
	1, // 1: scheduler.Scheduler.Heartbeat:input_type -> scheduler.HeartbeatRequest
	2, // 2: scheduler.Scheduler.ReportResult:input_type -> scheduler.JobResultRequest
	3, // 3: scheduler.Scheduler.Heartbeat:output_type -> scheduler.Ack
	3, // 4: scheduler.Scheduler.ReportResult:output_type -> scheduler.Ack
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scheduler_proto_init() }
func file_proto_scheduler_proto_init() {
	if File_proto_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scheduler_proto_rawDesc), len(file_proto_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scheduler_proto_goTypes,
		DependencyIndexes: file_proto_scheduler_proto_depIdxs,
		EnumInfos:         file_proto_scheduler_proto_enumTypes,
		MessageInfos:      file_proto_scheduler_proto_msgTypes,
	}.Build()
	File_proto_scheduler_proto = out.File
	file_proto_scheduler_proto_goTypes = nil
	file_proto_scheduler_proto_depIdxs = nil
}
