// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/proto/job.proto

package jobpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IdempotenceyKey string                 `protobuf:"bytes,1,opt,name=idempotencey_key,json=idempotenceyKey,proto3" json:"idempotencey_key,omitempty"`
	JobType         string                 `protobuf:"bytes,2,opt,name=job_type,json=jobType,proto3" json:"job_type,omitempty"`
	ScheduleAt      string                 `protobuf:"bytes,3,opt,name=schedule_at,json=scheduleAt,proto3" json:"schedule_at,omitempty"`
	Payload         []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateJobRequest) Reset() {
	*x = CreateJobRequest{}
	mi := &file_internal_proto_job_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateJobRequest) ProtoMessage() {}

func (x *CreateJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateJobRequest.ProtoReflect.Descriptor instead.
func (*CreateJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_proto_rawDescGZIP(), []int{0}
}

func (x *CreateJobRequest) GetIdempotenceyKey() string {
	if x != nil {
		return x.IdempotenceyKey
	}
	return ""
}

func (x *CreateJobRequest) GetJobType() string {
	if x != nil {
		return x.JobType
	}
	return ""
}

func (x *CreateJobRequest) GetScheduleAt() string {
	if x != nil {
		return x.ScheduleAt
	}
	return ""
}

func (x *CreateJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ModifyJobRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Payload        []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModifyJobRequest) Reset() {
	*x = ModifyJobRequest{}
	mi := &file_internal_proto_job_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyJobRequest) ProtoMessage() {}

func (x *ModifyJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyJobRequest.ProtoReflect.Descriptor instead.
func (*ModifyJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_proto_rawDescGZIP(), []int{1}
}

func (x *ModifyJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ModifyJobRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ModifyJobRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type CancelJobRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelJobRequest) Reset() {
	*x = CancelJobRequest{}
	mi := &file_internal_proto_job_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelJobRequest) ProtoMessage() {}

func (x *CancelJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelJobRequest.ProtoReflect.Descriptor instead.
func (*CancelJobRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_proto_rawDescGZIP(), []int{2}
}

func (x *CancelJobRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type TriggerNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerNowRequest) Reset() {
	*x = TriggerNowRequest{}
	mi := &file_internal_proto_job_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerNowRequest) ProtoMessage() {}

func (x *TriggerNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerNowRequest.ProtoReflect.Descriptor instead.
func (*TriggerNowRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerNowRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobResponse) Reset() {
	*x = JobResponse{}
	mi := &file_internal_proto_job_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobResponse) ProtoMessage() {}

func (x *JobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_job_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobResponse.ProtoReflect.Descriptor instead.
func (*JobResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_job_proto_rawDescGZIP(), []int{4}
}

func (x *JobResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_internal_proto_job_proto protoreflect.FileDescriptor

const file_internal_proto_job_proto_rawDesc = "" +
	"\n" +
	"\x18internal/proto/job.proto\x12\x03job\"\x93\x01\n" +
	"\x10CreateJobRequest\x12)\n" +
	"\x10idempotencey_key\x18\x01 \x01(\tR\x0fidempotenceyKey\x12\x19\n" +
	"\bjob_type\x18\x02 \x01(\tR\ajobType\x12\x1f\n" +
	"\vschedule_at\x18\x03 \x01(\tR\n" +
	"scheduleAt\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"l\n" +
	"\x10ModifyJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\")\n" +
	"\x10CancelJobRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"*\n" +
	"\x11TriggerNowRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"<\n" +
	"\vJobResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2\xe6\x01\n" +
	"\n" +
	"JobService\x124\n" +
	"\tCreateJob\x12\x15.job.CreateJobRequest\x1a\x10.job.JobResponse\x124\n" +
	"\tModifyJob\x12\x15.job.ModifyJobRequest\x1a\x10.job.JobResponse\x124\n" +
	"\tCancelJob\x12\x15.job.CancelJobRequest\x1a\x10.job.JobResponse\x126\n" +
	"\n" +
	"TriggerNow\x12\x16.job.TriggerNowRequest\x1a\x10.job.JobResponseB\x16Z\x14internal/proto/jobpbb\x06proto3"

var (
	file_internal_proto_job_proto_rawDescOnce sync.Once
	file_internal_proto_job_proto_rawDescData []byte
)

func file_internal_proto_job_proto_rawDescGZIP() []byte {
	file_internal_proto_job_proto_rawDescOnce.Do(func() {
		file_internal_proto_job_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_job_proto_rawDesc), len(file_internal_proto_job_proto_rawDesc)))
	})
	return file_internal_proto_job_proto_rawDescData
}

var file_internal_proto_job_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_proto_job_proto_goTypes = []any{
	(*CreateJobRequest)(nil),  // 0: job.CreateJobRequest
	(*ModifyJobRequest)(nil),  // 1: job.ModifyJobRequest
	(*CancelJobRequest)(nil),  // 2: job.CancelJobRequest
	(*TriggerNowRequest)(nil), // 3: job.TriggerNowRequest
	(*JobResponse)(nil),       // 4: job.JobResponse
}
var file_internal_proto_job_proto_depIdxs = []int32{
	0, // 0: job.JobService.CreateJob:input_type -> job.CreateJobRequest
	1, // 1: job.JobService.ModifyJob:input_type -> job.ModifyJobRequest
	2, // 2: job.JobService.CancelJob:input_type -> job.CancelJobRequest
	3, // 3: job.JobService.TriggerNow:input_type -> job.TriggerNowRequest
	4, // 4: job.JobService.CreateJob:output_type -> job.JobResponse
	4, // 5: job.JobService.ModifyJob:output_type -> job.JobResponse
	4, // 6: job.JobService.CancelJob:output_type -> job.JobResponse
	4, // 7: job.JobService.TriggerNow:output_type -> job.JobResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_job_proto_init() }
func file_internal_proto_job_proto_init() {
	if File_internal_proto_job_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_job_proto_rawDesc), len(file_internal_proto_job_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_job_proto_goTypes,
		DependencyIndexes: file_internal_proto_job_proto_depIdxs,
		MessageInfos:      file_internal_proto_job_proto_msgTypes,
	}.Build()
	File_internal_proto_job_proto = out.File
	file_internal_proto_job_proto_goTypes = nil
	file_internal_proto_job_proto_depIdxs = nil
}
