// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/proto/admin/api_key.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scopes        []string               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyRequest) Reset() {
	*x = CreateApiKeyRequest{}
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyRequest) ProtoMessage() {}

func (x *CreateApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_api_key_proto_rawDescGZIP(), []int{0}
}

func (x *CreateApiKeyRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CreateApiKeyRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type CreateApiKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateApiKeyResponse) Reset() {
	*x = CreateApiKeyResponse{}
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateApiKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateApiKeyResponse) ProtoMessage() {}

func (x *CreateApiKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateApiKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateApiKeyResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_api_key_proto_rawDescGZIP(), []int{1}
}

func (x *CreateApiKeyResponse) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

type RevokeApiKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeApiKeyRequest) Reset() {
	*x = RevokeApiKeyRequest{}
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeApiKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeApiKeyRequest) ProtoMessage() {}

func (x *RevokeApiKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_api_key_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeApiKeyRequest.ProtoReflect.Descriptor instead.
func (*RevokeApiKeyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_api_key_proto_rawDescGZIP(), []int{2}
}

func (x *RevokeApiKeyRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

var File_internal_proto_admin_api_key_proto protoreflect.FileDescriptor

const file_internal_proto_admin_api_key_proto_rawDesc = "" +
	"\n" +
	"\"internal/proto/admin/api_key.proto\x12\x05admin\x1a\x1bgoogle/protobuf/empty.proto\"D\n" +
	"\x13CreateApiKeyRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x16\n" +
	"\x06scopes\x18\x02 \x03(\tR\x06scopes\"/\n" +
	"\x14CreateApiKeyResponse\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\",\n" +
	"\x13RevokeApiKeyRequest\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId2\x90\x01\n" +
	"\rApiKeyService\x12A\n" +
	"\x06Create\x12\x1a.admin.CreateApiKeyRequest\x1a\x1b.admin.CreateApiKeyResponse\x12<\n" +
	"\x06Revoke\x12\x1a.admin.RevokeApiKeyRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cinternal/proto/admin;adminpbb\x06proto3"

var (
	file_internal_proto_admin_api_key_proto_rawDescOnce sync.Once
	file_internal_proto_admin_api_key_proto_rawDescData []byte
)

func file_internal_proto_admin_api_key_proto_rawDescGZIP() []byte {
	file_internal_proto_admin_api_key_proto_rawDescOnce.Do(func() {
		file_internal_proto_admin_api_key_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_admin_api_key_proto_rawDesc), len(file_internal_proto_admin_api_key_proto_rawDesc)))
	})
	return file_internal_proto_admin_api_key_proto_rawDescData
}

var file_internal_proto_admin_api_key_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_admin_api_key_proto_goTypes = []any{
	(*CreateApiKeyRequest)(nil),  // 0: admin.CreateApiKeyRequest
	(*CreateApiKeyResponse)(nil), // 1: admin.CreateApiKeyResponse
	(*RevokeApiKeyRequest)(nil),  // 2: admin.RevokeApiKeyRequest
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_internal_proto_admin_api_key_proto_depIdxs = []int32{
	0, // 0: admin.ApiKeyService.Create:input_type -> admin.CreateApiKeyRequest
	2, // 1: admin.ApiKeyService.Revoke:input_type -> admin.RevokeApiKeyRequest
	1, // 2: admin.ApiKeyService.Create:output_type -> admin.CreateApiKeyResponse
	3, // 3: admin.ApiKeyService.Revoke:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_admin_api_key_proto_init() }
func file_internal_proto_admin_api_key_proto_init() {
	if File_internal_proto_admin_api_key_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_admin_api_key_proto_rawDesc), len(file_internal_proto_admin_api_key_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_admin_api_key_proto_goTypes,
		DependencyIndexes: file_internal_proto_admin_api_key_proto_depIdxs,
		MessageInfos:      file_internal_proto_admin_api_key_proto_msgTypes,
	}.Build()
	File_internal_proto_admin_api_key_proto = out.File
	file_internal_proto_admin_api_key_proto_goTypes = nil
	file_internal_proto_admin_api_key_proto_depIdxs = nil
}
