// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/proto/admin/app.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppName       string                 `protobuf:"bytes,1,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppEmail      string                 `protobuf:"bytes,2,opt,name=app_email,json=appEmail,proto3" json:"app_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAppRequest) Reset() {
	*x = RegisterAppRequest{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppRequest) ProtoMessage() {}

func (x *RegisterAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppRequest.ProtoReflect.Descriptor instead.
func (*RegisterAppRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterAppRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *RegisterAppRequest) GetAppEmail() string {
	if x != nil {
		return x.AppEmail
	}
	return ""
}

type RegisterAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAppResponse) Reset() {
	*x = RegisterAppResponse{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAppResponse) ProtoMessage() {}

func (x *RegisterAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAppResponse.ProtoReflect.Descriptor instead.
func (*RegisterAppResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterAppResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type ListAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsRequest) Reset() {
	*x = ListAppsRequest{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsRequest) ProtoMessage() {}

func (x *ListAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsRequest.ProtoReflect.Descriptor instead.
func (*ListAppsRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{2}
}

type ListAppsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Apps          []*App                 `protobuf:"bytes,1,rep,name=apps,proto3" json:"apps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAppsResponse) Reset() {
	*x = ListAppsResponse{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppsResponse) ProtoMessage() {}

func (x *ListAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAppsResponse.ProtoReflect.Descriptor instead.
func (*ListAppsResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{3}
}

func (x *ListAppsResponse) GetApps() []*App {
	if x != nil {
		return x.Apps
	}
	return nil
}

type App struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	AppName       string                 `protobuf:"bytes,2,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppEmail      string                 `protobuf:"bytes,3,opt,name=app_email,json=appEmail,proto3" json:"app_email,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Tier          string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *App) Reset() {
	*x = App{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *App) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*App) ProtoMessage() {}

func (x *App) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use App.ProtoReflect.Descriptor instead.
func (*App) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{4}
}

func (x *App) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *App) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *App) GetAppEmail() string {
	if x != nil {
		return x.AppEmail
	}
	return ""
}

func (x *App) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *App) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

type BlockAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockAppRequest) Reset() {
	*x = BlockAppRequest{}
	mi := &file_internal_proto_admin_app_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockAppRequest) ProtoMessage() {}

func (x *BlockAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_app_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockAppRequest.ProtoReflect.Descriptor instead.
func (*BlockAppRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_app_proto_rawDescGZIP(), []int{5}
}

func (x *BlockAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

var File_internal_proto_admin_app_proto protoreflect.FileDescriptor

const file_internal_proto_admin_app_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/proto/admin/app.proto\x12\x05admin\x1a\x1bgoogle/protobuf/empty.proto\"L\n" +
	"\x12RegisterAppRequest\x12\x19\n" +
	"\bapp_name\x18\x01 \x01(\tR\aappName\x12\x1b\n" +
	"\tapp_email\x18\x02 \x01(\tR\bappEmail\",\n" +
	"\x13RegisterAppResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"\x11\n" +
	"\x0fListAppsRequest\"2\n" +
	"\x10ListAppsResponse\x12\x1e\n" +
	"\x04apps\x18\x01 \x03(\v2\n" +
	".admin.AppR\x04apps\"\x80\x01\n" +
	"\x03App\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x19\n" +
	"\bapp_name\x18\x02 \x01(\tR\aappName\x12\x1b\n" +
	"\tapp_email\x18\x03 \x01(\tR\bappEmail\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\"(\n" +
	"\x0fBlockAppRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId2\x89\x02\n" +
	"\n" +
	"AppService\x12D\n" +
	"\vRegisterApp\x12\x19.admin.RegisterAppRequest\x1a\x1a.admin.RegisterAppResponse\x12;\n" +
	"\bListApps\x12\x16.admin.ListAppsRequest\x1a\x17.admin.ListAppsResponse\x12:\n" +
	"\bBlockApp\x12\x16.admin.BlockAppRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\n" +
	"UnblockApp\x12\x16.admin.BlockAppRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cinternal/proto/admin;adminpbb\x06proto3"

var (
	file_internal_proto_admin_app_proto_rawDescOnce sync.Once
	file_internal_proto_admin_app_proto_rawDescData []byte
)

func file_internal_proto_admin_app_proto_rawDescGZIP() []byte {
	file_internal_proto_admin_app_proto_rawDescOnce.Do(func() {
		file_internal_proto_admin_app_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_admin_app_proto_rawDesc), len(file_internal_proto_admin_app_proto_rawDesc)))
	})
	return file_internal_proto_admin_app_proto_rawDescData
}

var file_internal_proto_admin_app_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_admin_app_proto_goTypes = []any{
	(*RegisterAppRequest)(nil),  // 0: admin.RegisterAppRequest
	(*RegisterAppResponse)(nil), // 1: admin.RegisterAppResponse
	(*ListAppsRequest)(nil),     // 2: admin.ListAppsRequest
	(*ListAppsResponse)(nil),    // 3: admin.ListAppsResponse
	(*App)(nil),                 // 4: admin.App
	(*BlockAppRequest)(nil),     // 5: admin.BlockAppRequest
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_internal_proto_admin_app_proto_depIdxs = []int32{
	4, // 0: admin.ListAppsResponse.apps:type_name -> admin.App
	0, // 1: admin.AppService.RegisterApp:input_type -> admin.RegisterAppRequest
	2, // 2: admin.AppService.ListApps:input_type -> admin.ListAppsRequest
	5, // 3: admin.AppService.BlockApp:input_type -> admin.BlockAppRequest
	5, // 4: admin.AppService.UnblockApp:input_type -> admin.BlockAppRequest
	1, // 5: admin.AppService.RegisterApp:output_type -> admin.RegisterAppResponse
	3, // 6: admin.AppService.ListApps:output_type -> admin.ListAppsResponse
	6, // 7: admin.AppService.BlockApp:output_type -> google.protobuf.Empty
	6, // 8: admin.AppService.UnblockApp:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_admin_app_proto_init() }
func file_internal_proto_admin_app_proto_init() {
	if File_internal_proto_admin_app_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_admin_app_proto_rawDesc), len(file_internal_proto_admin_app_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_admin_app_proto_goTypes,
		DependencyIndexes: file_internal_proto_admin_app_proto_depIdxs,
		MessageInfos:      file_internal_proto_admin_app_proto_msgTypes,
	}.Build()
	File_internal_proto_admin_app_proto = out.File
	file_internal_proto_admin_app_proto_goTypes = nil
	file_internal_proto_admin_app_proto_depIdxs = nil
}
