// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/proto/admin/email.proto

package adminpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigureEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	FromEmail     string                 `protobuf:"bytes,3,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureEmailRequest) Reset() {
	*x = ConfigureEmailRequest{}
	mi := &file_internal_proto_admin_email_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureEmailRequest) ProtoMessage() {}

func (x *ConfigureEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_admin_email_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigureEmailRequest.ProtoReflect.Descriptor instead.
func (*ConfigureEmailRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_admin_email_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigureEmailRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ConfigureEmailRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ConfigureEmailRequest) GetFromEmail() string {
	if x != nil {
		return x.FromEmail
	}
	return ""
}

var File_internal_proto_admin_email_proto protoreflect.FileDescriptor

const file_internal_proto_admin_email_proto_rawDesc = "" +
	"\n" +
	" internal/proto/admin/email.proto\x12\x05admin\x1a\x1bgoogle/protobuf/empty.proto\"i\n" +
	"\x15ConfigureEmailRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"from_email\x18\x03 \x01(\tR\tfromEmail2Q\n" +
	"\fEmailService\x12A\n" +
	"\tConfigure\x12\x1c.admin.ConfigureEmailRequest\x1a\x16.google.protobuf.EmptyB\x1eZ\x1cinternal/proto/admin;adminpbb\x06proto3"

var (
	file_internal_proto_admin_email_proto_rawDescOnce sync.Once
	file_internal_proto_admin_email_proto_rawDescData []byte
)

func file_internal_proto_admin_email_proto_rawDescGZIP() []byte {
	file_internal_proto_admin_email_proto_rawDescOnce.Do(func() {
		file_internal_proto_admin_email_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_admin_email_proto_rawDesc), len(file_internal_proto_admin_email_proto_rawDesc)))
	})
	return file_internal_proto_admin_email_proto_rawDescData
}

var file_internal_proto_admin_email_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_admin_email_proto_goTypes = []any{
	(*ConfigureEmailRequest)(nil), // 0: admin.ConfigureEmailRequest
	(*emptypb.Empty)(nil),         // 1: google.protobuf.Empty
}
var file_internal_proto_admin_email_proto_depIdxs = []int32{
	0, // 0: admin.EmailService.Configure:input_type -> admin.ConfigureEmailRequest
	1, // 1: admin.EmailService.Configure:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_admin_email_proto_init() }
func file_internal_proto_admin_email_proto_init() {
	if File_internal_proto_admin_email_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_admin_email_proto_rawDesc), len(file_internal_proto_admin_email_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_admin_email_proto_goTypes,
		DependencyIndexes: file_internal_proto_admin_email_proto_depIdxs,
		MessageInfos:      file_internal_proto_admin_email_proto_msgTypes,
	}.Build()
	File_internal_proto_admin_email_proto = out.File
	file_internal_proto_admin_email_proto_goTypes = nil
	file_internal_proto_admin_email_proto_depIdxs = nil
}
